### ISSUE TITLE
Crash with bundle tooltip

### ISSUE THREAD

**Issue by cntrik** [vlad2305m/AkashicTomeOfToolsFabric#7]
[2022-07-27-6.log](https://github.com/vlad2305m/AkashicTomeOfToolsFabric/files/9203531/2022-07-27-6.log)
modlist:
- akashictomeoftools 1.3.1
- architectury 5.10.33
- betterbeds 1.2.0 via jello
- c2me 0.2.0+alpha.8.2
- cloth-api 4.0.65
- cloth-config 7.0.73
- dynamicfps 2.2.0
- fabric 0.58.0+1.19
- fabricloader 0.14.8
- ferritecore 4.2.1
- indium 1.0.6+mc1.19
- iris 1.2.6
- jade 7.7.0
- java 17
- jello 4.1.0+1.19
- krypton 0.2.0
- minecraft 1.19
- owo 0.7.3+1.19
- sodium 0.4.2+build.16
This affected both the vanilla bundle and dye bundle from Jello.
Dragon-Seeker concluded "It seems that akashictomeoftools add custom bundle tooltip stuff with ofB() method contained in one of there mixins."

net.minecraft.class_148: Rendering screen
at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
at java.util.ArrayList.get(Unknown Source) ~[?:?]
at net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
at net.minecraft.class_5684.handler$zbc000$ofB(class_5684.java:516) ~[client-intermediary.jar:?]
at net.minecraft.class_5684.method_32663(class_5684.java) ~[client-intermediary.jar:?]
at net.minecraft.class_437.method_32635(class_437.java:177) ~[client-intermediary.jar:?]
at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
at net.minecraft.class_437.method_32634(class_437.java:177) ~[client-intermediary.jar:?]
at net.minecraft.class_437.method_25409(class_437.java:169) ~[client-intermediary.jar:?]
at net.minecraft.class_481.method_25409(class_481.java:731) ~[client-intermediary.jar:?]
at net.minecraft.class_465.method_2380(class_465.java:189) ~[client-intermediary.jar:?]
at net.minecraft.class_481.method_25394(class_481.java:692) ~[client-intermediary.jar:?]
at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
... 6 more

**Comment by vlad2305m** [comment]
Try 1.3.2 (https://github.com/vlad2305m/AkashicTomeOfToolsFabric/releases/tag/1.3)
